### ISSUE TITLE
Can't use with python 3.10

### ISSUE THREAD

**Issue by Goddard** [NVIDIA-AI-IOT/nvidia-tao#1]
Looks like python removed something.
ImportError: cannot import name 'Iterable' from 'collections'

So I was unable to use with python 3.10

**Comment by ramanathan831** [comment]
Can you mention which notebook you are running
The Tensorflow notebooks run on python3.6
The Pytorch notebooks run on python3.7
TAO Deploy notebook run on python3.8

**Comment by Goddard** [comment]
This is just running the quick start for tao setup.  

https://catalog.ngc.nvidia.com/orgs/nvidia/teams/tao/resources/tao-getting-started

**Comment by ramanathan831** [comment]
Not clear with what's going wrong with the info you have provided thus far.
Please be more specific which model/notebook you are running and on how are you running TAO (there are 4 ways in the link you mentioned)

**Comment by Goddard** [comment]
Not running a notebook.  I am running the quickstart bash script.

**Comment by ramanathan831** [comment]
Can you key-in the command you are running?

**Comment by Goddard** [comment]
bash quickstart_launcher.sh

This script also has a bug where it tries to use the ngc binary, but it doesn't include the base directory which results in binary not found, but I think that is unrelated to the python package issues.

**Comment by ramanathan831** [comment]
Did you follow the steps here: https://docs.nvidia.com/tao/tao-toolkit/text/tao_toolkit_quick_start_guide.html#running-via-launcher ?

The aforementioned issue is not tied to this repo

**Comment by MalteEbner** [comment]
I got the same error:
```bash
ubuntu@ip-123-45-67-890:/GitHub/NvidiaTAOActiveLearning$ tao yolo_v4 train     -e /workspace/tao-experiments/yolo_v4/specs/yolo_v4_minneapple.txt     -r /workspace/tao-experiments/yolo_v4/experiment_dir_unpruned     --gpus 1     -k MY_API_KEY
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.10.6/bin/tao", line 5, in <module>
    from tlt.entrypoint.tao import main
  File "/home/ubuntu/.pyenv/versions/3.10.6/lib/python3.10/site-packages/tlt/entrypoint/tao.py", line 11, in <module>
    from tlt.components.instance_handler.builder import get_launcher
  File "/home/ubuntu/.pyenv/versions/3.10.6/lib/python3.10/site-packages/tlt/components/instance_handler/builder.py", line 12, in <module>
    from tlt.components.instance_handler.local_instance import LocalInstance
  File "/home/ubuntu/.pyenv/versions/3.10.6/lib/python3.10/site-packages/tlt/components/instance_handler/local_instance.py", line 15, in <module>
    from tabulate import tabulate
  File "/home/ubuntu/.pyenv/versions/3.10.6/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/home/ubuntu/.pyenv/versions/3.10.6/lib/python3.10/collections/__init__.py)
```

This is caused by tao using an outdated version of the tabulate package: https://github.com/astanin/python-tabulate/issues/227
