### ISSUE TITLE
tao_deploy notebook error

### ISSUE THREAD

**Issue by liviolima80** [NVIDIA-AI-IOT/nvidia-tao#4]
Good morning,
I tried to run the tao-deploy notebook in order to create a TensorRT engine for PeopleNet model. When I try to run the section 7) I got the following error:

/usr/local/lib/python3.8/dist-packages/pycuda/compyte/dtypes.py:120: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  reg.get_or_register_dtype("bool", np.bool)
Traceback (most recent call last):
  File "/usr/local/bin/detectnet_v2", line 8, in <module>
    sys.exit(main())
  File "<frozen cv.detectnet_v2.entrypoint.detectnet_v2>", line 12, in main
  File "<frozen cv.common.entrypoint.entrypoint_proto>", line 196, in launch_job
  File "<frozen cv.common.entrypoint.entrypoint_proto>", line 50, in get_modules
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "</usr/local/lib/python3.8/dist-packages/nvidia_tao_deploy/cv/detectnet_v2/scripts/evaluate.py>", line 3, in <module>
  File "<frozen cv.detectnet_v2.scripts.evaluate>", line 26, in <module>
  File "</usr/local/lib/python3.8/dist-packages/nvidia_tao_deploy/cv/detectnet_v2/inferencer.py>", line 1, in <module>
  File "<frozen cv.detectnet_v2.inferencer>", line 50, in <module>
  File "</usr/local/lib/python3.8/dist-packages/nvidia_tao_deploy/inferencer/utils.py>", line 1, in <module>
  File "<frozen inferencer.utils>", line 15, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pycuda/autoinit.py", line 7, in <module>
    from pycuda.tools import make_default_context
  File "/usr/local/lib/python3.8/dist-packages/pycuda/tools.py", line 49, in <module>
    _fill_dtype_registry(respect_windows=True)
  File "/usr/local/lib/python3.8/dist-packages/pycuda/compyte/dtypes.py", line 221, in _fill_dtype_registry
    fill_registry_with_c_types(
  File "/usr/local/lib/python3.8/dist-packages/pycuda/compyte/dtypes.py", line 120, in fill_registry_with_c_types
    reg.get_or_register_dtype("bool", np.bool)
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Any suggestions?

Regards

**Comment by ramanathan831** [comment]
As pointed out, this is a numpy version issue, will be fixed in the 5.0 release of TAO, which is a few weeks away
