### ISSUE TITLE
docker container for tao-deploy

### ISSUE THREAD

**Issue by liviolima80** [NVIDIA-AI-IOT/nvidia-tao#5]
Good morning,
I tried to create a docker container for using tao-deploy, starting from official nvidia container nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

Next, following the tao-deploy container and setup_env_colab.sh script I installed all the python packages.

When I tried to convert PeopleNet model to TensorRT engine with the following command

detectnet_v2 gen_trt_engine -m /home/ngc_content/ptm_models/peoplenet_vpruned_v2.3/resnet34_peoplenet_pruned.etlt -k $KEY -e $trt_experiment_spec --data_type $data_type --batch_size 1 --max_batch_size 1 --engine_file $trt_out_file_name

following the indications of colab container I got the following error:

Loading uff directly from the package source code
Traceback (most recent call last):
  File "/usr/local/bin/detectnet_v2", line 8, in <module>
    sys.exit(main())
  File "<frozen cv.detectnet_v2.entrypoint.detectnet_v2>", line 12, in main
  File "<frozen cv.common.entrypoint.entrypoint_proto>", line 196, in launch_job
  File "<frozen cv.common.entrypoint.entrypoint_proto>", line 50, in get_modules
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "</usr/local/lib/python3.8/dist-packages/nvidia_tao_deploy/cv/detectnet_v2/scripts/gen_trt_engine.py>", line 3, in <module>
  File "<frozen cv.detectnet_v2.scripts.gen_trt_engine>", line 19, in <module>
  File "</usr/local/lib/python3.8/dist-packages/nvidia_tao_deploy/cv/detectnet_v2/engine_builder.py>", line 1, in <module>
  File "<frozen cv.detectnet_v2.engine_builder>", line 38, in <module>
  File "</usr/local/lib/python3.8/dist-packages/nvidia_tao_deploy/engine/builder.py>", line 1, in <module>
  File "<frozen engine.builder>", line 28, in <module>
ValueError: not enough values to unpack (expected 4, got 3)

Any suggestions?

Regards

**Comment by ramanathan831** [comment]
can you post in general Nvidia tao forum, this is not a colab issue
https://forums.developer.nvidia.com/c/accelerated-computing/intelligent-video-analytics/tao-toolkit/17
